version: '3'

services:
  armario-mongo-express:
    container_name: armario_mongo_express
    image: mongo-express:0.54.0
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: 'armario-mongo'
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    depends_on:
      - armario-mongo
    networks:
      - armariobot_network

  armario-mongo:
    container_name: armario_mongo
    image: mongo:focal
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/MongoDB:/data/db
    networks:
      - armariobot_network

networks: 
  armariobot_network:
    external:
      name: armariobot_network
