version: '3.7'
services:
  armariobot:
    build: .
    container_name: armariobot
    environment:
      DISCORD_TOKEN: "OTQ4MjIzNTg3MjY4MDQ2ODQ5.Yh4sCA.C2Mrd72RNv5pkbDThy62VUFkoJ4"
      DISCORD_CLIENT_ID: "948223587268046849"
      DISCORD_GUILD_ID: "705513409814331462"
      MONGO_DB_HOST: armario-mongo
      MONGO_DB_NAME: armario
      MONGO_DB_USERNAME: root
      MONGO_DB_PASSWORD: root
    restart: unless-stopped
networks: 
  default:
    external:
      name: armariobot_network